import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Flarely — Real-time event notifications for developers',
  description: 'Know when anything important happens in your app. Send any event to Slack, Discord, Telegram, or email with one HTTP call. Free tier, open source, self-hostable.',
  metadataBase: new URL('https://getflarely.dev'),
  keywords: ['event notifications', 'developer alerts', 'discord notifications', 'slack alerts', 'webhook alerting', 'self-hosted', 'cron monitoring', 'developer tools'],
  authors: [{ name: 'Flarely' }],
  openGraph: {
    title: 'Flarely — Error & Event Notifications for Developers',
    description: 'Send real-time alerts from your app to Discord, Slack, or any webhook. Free tier included. Self-hostable open source.',
    url: 'https://getflarely.dev',
    siteName: 'Flarely',
    type: 'website',
    // Image is auto-generated by app/opengraph-image.tsx — do not hardcode
    // an images array here or it overrides the dynamic image.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Flarely — Error & Event Notifications for Developers',
    description: 'Send real-time alerts from your app to Discord or Slack. Free tier, open source.',
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: 'https://getflarely.dev',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-sans">{children}</body>
    </html>
  )
}
